CREATE TABLE `sap_process_order_operation_data`
(
	`OrderInternalBillOfOperations`          varchar(10) NOT NULL,
    `OrderIntBillOfOperationsItem`           varchar(8) NOT NULL,
	`ManufacturingOrder`                     varchar(12) NOT NULL,
	`ManufacturingOrderSequence`             varchar(6) NOT NULL,
	`MfgOrderSequenceText`                   varchar(40) DEFAULT NULL,
	`ManufacturingOrderOperation`            varchar(4) DEFAULT NULL,
	`ManufacturingOrderSubOperation`         varchar(4) DEFAULT NULL,
	`ManufacturingOrderCategory`             varchar(2) DEFAULT NULL,
	`ManufacturingOrderType`                 varchar(4) DEFAULT NULL,
	`MfgOrderOperationText`                  varchar(40) DEFAULT NULL,
	`OperationIsCreated`                     varchar(1) DEFAULT NULL,
	`OperationIsReleased`                    varchar(1) DEFAULT NULL,
	`OperationIsPrinted`                     varchar(1) DEFAULT NULL,
	`OperationIsConfirmed`                   varchar(1) DEFAULT NULL,
	`OperationIsPartiallyConfirmed`          varchar(1) DEFAULT NULL,
	`OperationIsDeleted`                     varchar(1) DEFAULT NULL,
	`OperationIsTechlyCompleted`             varchar(1) DEFAULT NULL,
	`OperationIsClosed`                      varchar(1) DEFAULT NULL,
	`OperationIsScheduled`                   varchar(1) DEFAULT NULL,
	`OperationIsPartiallyDelivered`          varchar(1) DEFAULT NULL,
	`OperationIsDelivered`                   varchar(1) DEFAULT NULL,
	`ProductionPlant`                        varchar(4) DEFAULT NULL,
	`WorkCenterInternalID`                   varchar(8) DEFAULT NULL,
	`WorkCenterTypeCode`                     varchar(1) DEFAULT NULL,
	`WorkCenter`                             varchar(8) DEFAULT NULL,
	`OperationControlProfile`                varchar(4) DEFAULT NULL,
	`OpErlstSchedldExecStrtDte`              varchar(80) DEFAULT NULL,
	`OpErlstSchedldExecStrtTme`              varchar(80) DEFAULT NULL,
	`OpErlstSchedldExecEndDte`               varchar(80) DEFAULT NULL,
	`OpErlstSchedldExecEndTme`               varchar(80) DEFAULT NULL,
	`OpActualExecutionStartDate`             varchar(80) DEFAULT NULL,
	`OpActualExecutionStartTime`             varchar(80) DEFAULT NULL,
	`OpActualExecutionEndDate`               varchar(80) DEFAULT NULL,
	`OpActualExecutionEndTime                varchar(80) DEFAULT NULL,
	`ErlstSchedldExecDurnInWorkdays`         int(80) DEFAULT NULL,
	`OpActualExecutionDays`                  int(80) DEFAULT NULL,
	`OperationUnit`                          varchar(3) DEFAULT NULL,
	`OpPlannedTotalQuantity`                 varchar(80) DEFAULT NULL,
	`OpTotalConfirmedYieldQty`               varchar(80) DEFAULT NULL,
	`LastChangeDateTime`                     varchar(14) DEFAULT NULL,
    PRIMARY KEY (`OrderInternalBillOfOperations`, `OrderIntBillOfOperationsItem`, `ManufacturingOrder`, `ManufacturingOrderSequence`),
    CONSTRAINT `SAPProcessOrderOperationData_fk` FOREIGN KEY (`ManufacturingOrder`) REFERENCES `sap_process_order_operation_general_data` (`ManufacturingOrder`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;